Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

============ RESTART: C:\Users\Mjolnir\Desktop\PYTHON\ASSIGNMENT.PY ============
AVERAGE OF THREE NUMBERS

 number1 =23
 number2 =26
 number3 =30
26.333333333333332
INCOME TAX

enter the Gross income(y) = $ 50000
Number of dependents = 3
6200.0
STUDENT DATA

Student Name Jatinder Pal Singh
enter SID 21104159
enter Gender M
Course Name Physics
CGPA9.9
['Jatinder Pal Singh', '21104159', 'M', 'Physics', 9.9]
MARKS OF 5 STUDENTS

Marks of student1 = 23
Marks of student2 = 33
Marks of student3 = 36
Marks of student4 = 40
Marks of student5 = 39
[23, 33, 36, 40, 39]
COLOR

['Red', 'Green', 'White', 'Pink', 'Yellow']
['Red', 'Green', 'White', 'Purple', 'Yellow']
