Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

============ RESTART: C:\Users\Mjolnir\Desktop\PYTHON\ASSIGNMENT2.py ===========
QUESTION 1:

35
egaugnal evitisnes esac a si nohtyP
 a case sensitive 
Python is object oriented language
10
Pythonisacasesensitivelanguage
QUESTION 2:

 Hey, Jatinder Pal Singh here!
 My SID is 21104059
 Iam from Electrical Engineering department and my CGPA is 9.9
QUESTION 3:

8
58
50
224
40
14
0
QUESTION 4:

enter number 1: 23
enter number 2: 33
enter number 3: 3
n2 is gratest
QUESTION 5:

TYPE ANY SENTENCE:
my name jatinder
YES
QUESTION 6:

LENGTH 1 : 32
LENGTH 2 : 23
LENGTH 3 : 3
NO

